// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPurchaseOrdersApp.Database;

#nullable disable

namespace RazorPurchaseOrdersApp.Migrations
{
    [DbContext(typeof(ContextDBApp))]
    partial class ContextDBAppModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RazorPurchaseOrdersApp.Models.BurgerDBOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BurgerDBName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("FinalDBPrice")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("MenuOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
